### ISSUE TITLE
Order posts from newest to older by default.

### ISSUE THREAD

**Issue by voldemortensen** [scantjs/scant#5]
Currently posts don't have a defined order, so they appear in any order. By default they should appear newest to oldest.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/7786383/57814330-96951900-7730-11e9-9531-0dfcb7c7374a.png">

**Comment by rdela** [comment]
So I opened a PR on example site, https://github.com/scantjs/scant-example-site/pull/9, that I used to test the fix in https://github.com/scantjs/scant/pull/8 with. If you want to test this that should help!
