### ISSUE TITLE
Logo (re)design

### ISSUE THREAD

**Issue by rdela** [scantjs/scant#7]
See:
https://github.com/scantjs/scant-example-site/pull/6#issuecomment-493638439

> I'm not 100% sold on the logo and colors, but it's much better than not having anything at all.

Current logo + wordmark:
https://github.com/scantjs/scant-example-site/tree/master/src/assets

Let's workshop this and make everybody happier.

**Comment by rdela** [comment]
For the logo, maybe a spoon not quite full of sugar?
https://start.duckduckgo.com/?q=scant+teaspoon+tablespoon&ia=web
https://start.duckduckgo.com/?q=scant+teaspoon+tablespoon&iax=images&ia=images

**Comment by voldemortensen** [comment]
> For the logo, maybe a spoon not quite full of sugar?
> https://start.duckduckgo.com/?q=scant+teaspoon+tablespoon&ia=web
> https://start.duckduckgo.com/?q=scant+teaspoon+tablespoon&iax=images&ia=images

I really like that idea. I had no idea a "scant" was a measurement.

**Comment by rdela** [comment]
## on white
![scant-logo-on-white](https://user-images.githubusercontent.com/74381/58378222-5d855180-7f45-11e9-90fb-c64e2435659b.png)

## on black
![scant-logo-on-black](https://user-images.githubusercontent.com/74381/58378225-5fe7ab80-7f45-11e9-94d0-f5997dab94db.png)

## [League Gothic (OSS!)](https://www.theleagueofmoveabletype.com/league-gothic)
![scant-logo-on-white-League-Gothic](https://user-images.githubusercontent.com/74381/58378226-637b3280-7f45-11e9-9611-592be950f768.png)

## [Arial Rounded MT Bold (Linotype)](https://www.linotype.com/164762/arial-rounded-bold-product.html)
![scant-logo-on-white-Arial-Rounded-MT-Bold](https://user-images.githubusercontent.com/74381/58378233-9c1b0c00-7f45-11e9-975a-360b015eef12.png)

## [Snell Roundhand](https://www.fonts.com/font/linotype/snell-roundhand/story) ([Linotype](https://www.linotype.com/1196135/snell-roundhand-family.html))
![scant-logo-on-white-Snell-Roundhand](https://user-images.githubusercontent.com/74381/58378237-a3dab080-7f45-11e9-8f50-afb2a8e7e88d.png)

**Comment by voldemortensen** [comment]
I really like these. I think my favorite is the Leage Gothic one. The only thing I can think of is to maybe add some sugar or something in the bowl of the spoon.
